### ISSUE TITLE
Unbound variable gpg_check

### ISSUE THREAD

**Issue by braunsonm** [mmanciop/rpm-package-resource#1]
Hey @mmanciop 

Not sure if you still maintain this tool, but I think there's a problem with how `gpg_check` is defined. Defining and then using it like this: https://github.com/mmanciop/rpm-package-resource/blob/main/assets/check#L70

Means that the variable won't always exist, so the `set -u` throws an error about unbound variable.

Minimal example:
```yaml
resource_types:

- name: rpm-package-resource
  type: registry-image
  source:
    repository: mmanciop/rpm-package-resource
    tag: latest

resources:
- name: my-happy-rpm-package
  type: rpm-package
  source:
    repository:
      url: https://blah.blah/agent/generic/x86_64
      gpg_check: false
    package: my-happy-package
    architecture: x86_64
```

Results in the error: `/opt/resource/check: line 82: gpg_check: unbound variable`
